DEV: Adds method to update an invite
discourse/discourse_api pull request #229
Opened 2021-05-06 01:25 UTC by Ahmedgagan

@oblakeerickson

2021-05-06 21:19 UTC, oblakeerickson requested changes
Looks good! Could you also add a spec?

2021-05-06 21:21 UTC, Ahmedgagan commented
Yes, trying to add it, but we need invite id to update any invite. Trying to get the id

2021-05-06 22:21 UTC, Ahmedgagan commented
@oblakeerickson Added a commit with RSpec

2021-05-07 18:59 UTC, oblakeerickson approved these changes

2021-05-07 18:59 UTC, merged